// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: string.proto

package com.autohome.kafka;

public final class KafkaEncoder {
  private KafkaEncoder() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LoggerOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string log = 1;
    boolean hasLog();
    String getLog();
  }
  public static final class Logger extends
      com.google.protobuf.GeneratedMessage
      implements LoggerOrBuilder {
    // Use Logger.newBuilder() to construct.
    private Logger(Builder builder) {
      super(builder);
    }
    private Logger(boolean noInit) {}
    
    private static final Logger defaultInstance;
    public static Logger getDefaultInstance() {
      return defaultInstance;
    }
    
    public Logger getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.autohome.kafka.KafkaEncoder.internal_static_nxcjh_Logger_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.autohome.kafka.KafkaEncoder.internal_static_nxcjh_Logger_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string log = 1;
    public static final int LOG_FIELD_NUMBER = 1;
    private java.lang.Object log_;
    public boolean hasLog() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getLog() {
      java.lang.Object ref = log_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          log_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLogBytes() {
      java.lang.Object ref = log_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        log_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      log_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasLog()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getLogBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getLogBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.autohome.kafka.KafkaEncoder.Logger parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.autohome.kafka.KafkaEncoder.Logger parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.autohome.kafka.KafkaEncoder.Logger parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.autohome.kafka.KafkaEncoder.Logger parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.autohome.kafka.KafkaEncoder.Logger parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.autohome.kafka.KafkaEncoder.Logger parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.autohome.kafka.KafkaEncoder.Logger parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.autohome.kafka.KafkaEncoder.Logger parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.autohome.kafka.KafkaEncoder.Logger parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.autohome.kafka.KafkaEncoder.Logger parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.autohome.kafka.KafkaEncoder.Logger prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.autohome.kafka.KafkaEncoder.LoggerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.autohome.kafka.KafkaEncoder.internal_static_nxcjh_Logger_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.autohome.kafka.KafkaEncoder.internal_static_nxcjh_Logger_fieldAccessorTable;
      }
      
      // Construct using com.autohome.kafka.KafkaEncoder.Logger.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        log_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.autohome.kafka.KafkaEncoder.Logger.getDescriptor();
      }
      
      public com.autohome.kafka.KafkaEncoder.Logger getDefaultInstanceForType() {
        return com.autohome.kafka.KafkaEncoder.Logger.getDefaultInstance();
      }
      
      public com.autohome.kafka.KafkaEncoder.Logger build() {
        com.autohome.kafka.KafkaEncoder.Logger result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.autohome.kafka.KafkaEncoder.Logger buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.autohome.kafka.KafkaEncoder.Logger result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.autohome.kafka.KafkaEncoder.Logger buildPartial() {
        com.autohome.kafka.KafkaEncoder.Logger result = new com.autohome.kafka.KafkaEncoder.Logger(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.log_ = log_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.autohome.kafka.KafkaEncoder.Logger) {
          return mergeFrom((com.autohome.kafka.KafkaEncoder.Logger)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.autohome.kafka.KafkaEncoder.Logger other) {
        if (other == com.autohome.kafka.KafkaEncoder.Logger.getDefaultInstance()) return this;
        if (other.hasLog()) {
          setLog(other.getLog());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasLog()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              log_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string log = 1;
      private java.lang.Object log_ = "";
      public boolean hasLog() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getLog() {
        java.lang.Object ref = log_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          log_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLog(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        log_ = value;
        onChanged();
        return this;
      }
      public Builder clearLog() {
        bitField0_ = (bitField0_ & ~0x00000001);
        log_ = getDefaultInstance().getLog();
        onChanged();
        return this;
      }
      void setLog(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        log_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:nxcjh.Logger)
    }
    
    static {
      defaultInstance = new Logger(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:nxcjh.Logger)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_nxcjh_Logger_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_nxcjh_Logger_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014string.proto\022\005nxcjh\"\025\n\006Logger\022\013\n\003log\030\001" +
      " \002(\tB\"\n\022com.autohome.kafkaB\014KafkaEncoder"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_nxcjh_Logger_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_nxcjh_Logger_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_nxcjh_Logger_descriptor,
              new java.lang.String[] { "Log", },
              com.autohome.kafka.KafkaEncoder.Logger.class,
              com.autohome.kafka.KafkaEncoder.Logger.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
